version: "3.2"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./src:/app
      - node_modules:/app/node_modules
    command: /usr/local/wait-for-it.sh db:5432 -- yarn run dev
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - webnet
    depends_on:
      - db

  db:
    image: postgres:11
    volumes:
      - ./docker/init-user-db.sh/:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - webnet
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

networks:
  webnet:

volumes:
  node_modules:
